version: 0.0
os: linux
files:
- source: src/
  destination: /opt/myapp/src
permissions:
- object: /opt/myapp/src
  pattern: '**'
  owner: ec2-user
  group: ec2-user
hooks:
  BeforeInstall:
  - location: scripts/before_install.sh
    runas: root
  AfterInstall:
  - location: scripts/after_install.sh
    runas: root
  ApplicationStart:
  - location: scripts/start.sh
    runas: root
  HealthCheck:
  - location: scripts/health_check.sh
    runas: root
