name: CI-CD (GitHub → CodeDeploy)

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write         # OIDC!
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    #environment: AWS-Secrets-for Github-Actions   # uncomment if using Environment secrets

    steps:
      - name: Checking out the Code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}
          audience: sts.amazonaws.com

      - name: Package bundle (appspec at root)
        run: |
          rm -rf bundle artifact.zip
          mkdir -p bundle
          cp -r src bundle/src
          cp -r scripts bundle/scripts
          cp appspec.yml bundle/
          (cd bundle && zip -r ../artifact.zip .)

      - name: Upload artifact to S3
        run: |
          aws s3 cp artifact.zip s3://${{ secrets.ARTIFACTS_BUCKET }}/github-only/artifact-${{ github.sha }}.zip

      - name: Deploy via CodeDeploy
        env:
          CD_APP: ${{ secrets.CD_APP }}
          CD_DG:  ${{ secrets.CD_DG }}
        run: |
          aws deploy create-deployment \
            --application-name "$CD_APP" \
            --deployment-group-name "$CD_DG" \
            --s3-location bucket=${{ secrets.ARTIFACTS_BUCKET }},bundleType=zip,key=github-only/artifact-${{ github.sha }}.zip

      # Optional: prove identity
      - name: Who am I in AWS?
        run: aws sts get-caller-identity
